name: AWS CDK build, synth, test 

on:
  push:
    branches: [ "aws-cdk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: synthesize - cdk synth
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'synth'
        actions_comment: true



