name: flask rest build, save

on:
  push:
    branches: [ "python-rest" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.x]

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Use python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Build
      run: pip install -r requirement.txt

    - name: Tests
      run: |
        python -m coverage run -m unittest
        python -m coverage report
        python -m coverage html

    - name: upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: 'test-coverage'
        path: htmlcov
        retention-days: 1
  


